In [10]:
import sys 
print("User Current Version:-", sys.version)

User Current Version:- 3.10.6 (main, Aug 10 2022, 11:40:04) [GCC 11.3.0]


In [15]:
pip install --upgrade pip

Note: you may need to restart the kernel to use updated packages.


In [1]:
!pip install tensorflow;

In [2]:
!pip install matplotlib

In [3]:
!pip install sklearn 

In [4]:
!pip install pandas

In [1]:
import os;
import tensorflow as tf;
import pandas as pd;
import numpy as np;
from tensorflow.keras.layers import TextVectorization
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dropout, Bidirectional, Dense, Embedding # Biderectional layer is modifier on top of the LSTM layer , dropout - regulerization

2022-10-26 06:21:39.351226: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-10-26 06:21:43.182975: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-10-26 06:21:43.183035: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2022-10-26 06:21:43.552817: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2022-10-26 06:21:52.673560: W tensorflow/stream_executor/platform/de

In [30]:
!pip list

Package                      Version
---------------------------- -----------
absl-py                      1.3.0
anyio                        3.6.2
argon2-cffi                  21.3.0
argon2-cffi-bindings         21.2.0
asttokens                    2.0.8
astunparse                   1.6.3
attrs                        22.1.0
Babel                        2.10.3
backcall                     0.2.0
beautifulsoup4               4.11.1
bleach                       5.0.1
cachetools                   5.2.0
certifi                      2022.9.24
cffi                         1.15.1
charset-normalizer           2.1.1
contourpy                    1.0.5
cycler                       0.11.0
debugpy                      1.6.3
decorator                    5.1.1
defusedxml                   0.7.1
entrypoints                  0.4
executing                    1.1.1
fastjsonschema               2.16.2
flatbuffers                  22.9.24
fonttools                    4.38.0
gast                         0.4.0

In [2]:
CSV_PATH = os.path.join('CSV','train.csv')

In [3]:
data = pd.read_csv(CSV_PATH)

In [4]:
data.head()

id                                       comment_text  toxic  \
0  0000997932d777bf  Explanation\nWhy the edits made under my usern...      0   
1  000103f0d9cfb60f  D'aww! He matches this background colour I'm s...      0   
2  000113f07ec002fd  Hey man, I'm really not trying to edit war. It...      0   
3  0001b41b1c6bb37e  "\nMore\nI can't make any real suggestions on ...      0   
4  0001d958c54c6e35  You, sir, are my hero. Any chance you remember...      0   

   severe_toxic  obscene  threat  insult  identity_hate  
0             0        0       0       0              0  
1             0        0       0       0              0  
2             0        0       0       0              0  
3             0        0       0       0              0  
4             0        0       0       0              0

In [6]:
data.columns

Index(['id', 'comment_text', 'toxic', 'severe_toxic', 'obscene', 'threat',
       'insult', 'identity_hate'],
      dtype='object')

In [7]:
data.tail()

id                                       comment_text  \
159566  ffe987279560d7ff  ":::::And for the second time of asking, when ...   
159567  ffea4adeee384e90  You should be ashamed of yourself \n\nThat is ...   
159568  ffee36eab5c267c9  Spitzer \n\nUmm, theres no actual article for ...   
159569  fff125370e4aaaf3  And it looks like it was actually you who put ...   
159570  fff46fc426af1f9a  "\nAnd ... I really don't think you understand...   

        toxic  severe_toxic  obscene  threat  insult  identity_hate  
159566      0             0        0       0       0              0  
159567      0             0        0       0       0              0  
159568      0             0        0       0       0              0  
159569      0             0        0       0       0              0  
159570      0             0        0       0       0              0

In [8]:
data['comment_text'][0]

"Explanation\nWhy the edits made under my username Hardcore Metallica Fan were reverted? They weren't vandalisms, just closure on some GAs after I voted at New York Dolls FAC. And please don't remove the template from the talk page since I'm retired now.89.205.38.27"

In [9]:
data['comment_text'][1]

"D'aww! He matches this background colour I'm seemingly stuck with. Thanks.  (talk) 21:51, January 11, 2016 (UTC)"

In [10]:
data['comment_text'][2]

"Hey man, I'm really not trying to edit war. It's just that this guy is constantly removing relevant information and talking to me through edits instead of my talk page. He seems to care more about the formatting than the actual info."

In [11]:
data[data.columns[2:]]

toxic  severe_toxic  obscene  threat  insult  identity_hate
0           0             0        0       0       0              0
1           0             0        0       0       0              0
2           0             0        0       0       0              0
3           0             0        0       0       0              0
4           0             0        0       0       0              0
...       ...           ...      ...     ...     ...            ...
159566      0             0        0       0       0              0
159567      0             0        0       0       0              0
159568      0             0        0       0       0              0
159569      0             0        0       0       0              0
159570      0             0        0       0       0              0

[159571 rows x 6 columns]

In [12]:
data[data.columns[2:]].iloc[6]

toxic            1
severe_toxic     1
obscene          1
threat           0
insult           1
identity_hate    0
Name: 6, dtype: int64

In [13]:
data.iloc[6]

id                                           0002bcb3da6cb337
comment_text     COCKSUCKER BEFORE YOU PISS AROUND ON MY WORK
toxic                                                       1
severe_toxic                                                1
obscene                                                     1
threat                                                      0
insult                                                      1
identity_hate                                               0
Name: 6, dtype: object

In [14]:
data[data.columns[2:]]

toxic  severe_toxic  obscene  threat  insult  identity_hate
0           0             0        0       0       0              0
1           0             0        0       0       0              0
2           0             0        0       0       0              0
3           0             0        0       0       0              0
4           0             0        0       0       0              0
...       ...           ...      ...     ...     ...            ...
159566      0             0        0       0       0              0
159567      0             0        0       0       0              0
159568      0             0        0       0       0              0
159569      0             0        0       0       0              0
159570      0             0        0       0       0              0

[159571 rows x 6 columns]

In [15]:
data[data.columns[2:]].values

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       ...,
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [16]:
MAX_WORDS = 200000 #no of words in the vocabulory

In [17]:
vectorizer = TextVectorization(max_tokens=MAX_WORDS,
                               output_sequence_length=1800,
                               output_mode='int');


2022-10-26 06:22:42.582479: E tensorflow/stream_executor/cuda/cuda_driver.cc:265] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2022-10-26 06:22:42.582546: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (lasal-Azus-S15-X510UF): /proc/driver/nvidia/version does not exist
2022-10-26 06:22:42.612249: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [18]:
X = data['comment_text']
y = data[data.columns[2:]].values


In [22]:
vectorizer.adapt(X.values)

In [23]:
X.values

array(["Explanation\nWhy the edits made under my username Hardcore Metallica Fan were reverted? They weren't vandalisms, just closure on some GAs after I voted at New York Dolls FAC. And please don't remove the template from the talk page since I'm retired now.89.205.38.27",
       "D'aww! He matches this background colour I'm seemingly stuck with. Thanks.  (talk) 21:51, January 11, 2016 (UTC)",
       "Hey man, I'm really not trying to edit war. It's just that this guy is constantly removing relevant information and talking to me through edits instead of my talk page. He seems to care more about the formatting than the actual info.",
       ...,
       'Spitzer \n\nUmm, theres no actual article for prostitution ring.  - Crunch Captain.',
       'And it looks like it was actually you who put on the speedy to have the first version deleted now that I look at it.',
       '"\nAnd ... I really don\'t think you understand.  I came here and my idea was bad right away.  What kind of communit

In [24]:
vectorizer("Hello, This is a test text")[:6]

<tf.Tensor: shape=(6,), dtype=int64, numpy=array([288,  14,   9,   6, 697, 274])>

In [25]:
vectorized_text = vectorizer(X.values) #passing the numpy array to the vectorizer and vectorizing all text

2022-10-26 06:23:42.998694: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 253720368 exceeds 10% of free system memory.
2022-10-26 06:23:43.895838: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 2297822400 exceeds 10% of free system memory.


In [26]:
vectorized_text # 159571 - no of entries in the dataset , #1800 - output seq length wich is the max num of words a sentence might have. 0 s are given if it does to have that many words

<tf.Tensor: shape=(159571, 1800), dtype=int64, numpy=
array([[  645,    76,     2, ...,     0,     0,     0],
       [    1,    54,  2489, ...,     0,     0,     0],
       [  425,   441,    70, ...,     0,     0,     0],
       ...,
       [32445,  7392,   383, ...,     0,     0,     0],
       [    5,    12,   534, ...,     0,     0,     0],
       [    5,     8,   130, ...,     0,     0,     0]])>

In [27]:
vocab = vectorizer.get_vocabulary()
#print(*vocab, sep = ", ")

In [28]:
#Creating a data pipeline in tf. when we have data that cannot fit into memory
#MCSHABAP -data pipeline generation steps, map, cache,shuffle,batch,prefetch
dataset = tf.data.Dataset.from_tensor_slices((vectorized_text, y))

In [29]:
dataset = dataset.cache()

In [30]:
dataset = dataset.shuffle(160000) #160000 - buffersize

In [31]:
dataset = dataset.batch(16) #each batch has 16 samples

In [32]:
dataset = dataset.prefetch(8) # helps bottlenecks

In [33]:
batch_x,batch_y = dataset.as_numpy_iterator().next() #text in the vectorized format and the labels

2022-10-26 06:24:22.662938: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 2297822400 exceeds 10% of free system memory.


In [34]:
batch_x

array([[  149,    29,    77, ...,     0,     0,     0],
       [   76,    20,     7, ...,     0,     0,     0],
       [  793,    14,   415, ...,     0,     0,     0],
       ...,
       [17746, 88246,     6, ...,     0,     0,     0],
       [   32,     2,   108, ...,     0,     0,     0],
       [  194,    29,    77, ...,     0,     0,     0]])

In [35]:
batch_x.shape #batch size is 16

(16, 1800)

In [36]:
trainDataset = dataset.take(int(len(dataset)*.7)) # length of the 70% of data converted to int and taken from the dataset
validationDataset = dataset.skip(int(len(dataset)*.7)).take(int(len(dataset)*.2)) # validation partition skiping the first 70%
testDataset = dataset.skip(int(len(dataset)*.9)).take(int(len(dataset)*.1))


In [37]:
#Bidirectional??

In [38]:
model = Sequential()
# Create the embedding layer 
model.add(Embedding(MAX_WORDS+1, 32)) # The embedding has the max number of words +1 , +1 for the unknown words. and each embedding is 32 values in length
# Bidirectional LSTM Layer
model.add(Bidirectional(LSTM(32, activation='tanh'))) # this allows to pass information backwards and fowards accross the lstm. This is extremely important in text processing since the words prior to a particular word might have a meaning in the context of the word
#Ex: I don't hate you. if the sentence is taken word by word since hate is there it might be classified as toxic. But because of the don't modifier the values are changed
# Feature extractor Fully connected layers
model.add(Dense(128, activation='relu'))
model.add(Dense(256, activation='relu'))
model.add(Dense(128, activation='relu'))
# The ultimate layer maps to the number of outputs in our y values
model.add(Dense(6, activation='sigmoid'))

In [39]:
model.compile(loss='BinaryCrossentropy', optimizer='Adam')

In [40]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, None, 32)          6400032   
                                                                 
 bidirectional (Bidirectiona  (None, 64)               16640     
 l)                                                              
                                                                 
 dense (Dense)               (None, 128)               8320      
                                                                 
 dense_1 (Dense)             (None, 256)               33024     
                                                                 
 dense_2 (Dense)             (None, 128)               32896     
                                                                 
 dense_3 (Dense)             (None, 6)                 774       
                                                        

In [41]:
history = model.fit(trainDataset, epochs=1, validation_data=validationDataset)

2022-10-26 06:24:47.253406: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 2297822400 exceeds 10% of free system memory.


6981/6981 [==============================] - ETA: 0s - loss: 0.0624

2022-10-26 08:14:04.475024: W tensorflow/core/framework/cpu_allocator_impl.cc:82] Allocation of 2297822400 exceeds 10% of free system memory.


6981/6981 [==============================] - 6828s 976ms/step - loss: 0.0624 - val_loss: 0.0455


In [52]:
data.columns

Index(['id', 'comment_text', 'toxic', 'severe_toxic', 'obscene', 'threat',
       'insult', 'identity_hate'],
      dtype='object')

In [55]:
print('Enter the comment:')
text = input()
Input_comment = vectorizer(text)
print(Input_comment)
resIn = model.predict(np.expand_dims(Input_comment,0))
print(resIn)

Enter the comment:


 You suck


tf.Tensor([  7 397   0 ...   0   0   0], shape=(1800,), dtype=int64)
1/1 [==============================] - 0s 75ms/step
[[0.9745923  0.16044368 0.8949834  0.03380769 0.7252065  0.1112239 ]]


In [63]:
test_batch_X , test_batch_y = testDataset.as_numpy_iterator().next()

In [64]:
(model.predict(test_batch_X) > 0.5).astype(int)

1/1 [==============================] - 0s 158ms/step


array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [65]:
test_batch_y

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [66]:
from tensorflow.keras.metrics import Precision, Recall, CategoricalAccuracy


In [67]:
pre = Precision()
re = Recall()
acc = CategoricalAccuracy()


In [70]:
for batch in testDataset.as_numpy_iterator(): 
    # Unpack the batch 
    X_true, y_true = batch;
    # Make a prediction 
    yhat = model.predict(X_true);
    
    # Flatten the predictions
    y_true = y_true.flatten();
    yhat = yhat.flatten();
    
    pre.update_state(y_true, yhat);
    re.update_state(y_true, yhat);
    acc.update_state(y_true, yhat);


1/1 [==============================] - 0s 139ms/step


In [71]:
print(f'Precision: {pre.result().numpy()}, Recall:{re.result().numpy()}, Accuracy:{acc.result().numpy()}')

Precision: 0.8269484639167786, Recall:0.6993436813354492, Accuracy:0.46690070629119873


In [76]:
model.save('toxicityDetector.h5')

In [78]:
modelToxicityDetector = tf.keras.models.load_model('toxicityDetector.h5')

In [87]:
def score_comment(comment):
    vectorized_comment = vectorizer([comment])
    results = model.predict(vectorized_comment)
    
    text = ''
    for idx, col in enumerate(data.columns[2:]):
        text += '{}: {}\n'.format(col, results[0][idx]>0.5)
    
    return text



1/1 [==============================] - 0s 96ms/step


Traceback (most recent call last):
  File "/home/lasal/Development/test/test/lib/python3.10/site-packages/gradio/routes.py", line 298, in run_predict
    output = await app.blocks.process_api(
  File "/home/lasal/Development/test/test/lib/python3.10/site-packages/gradio/blocks.py", line 790, in process_api
    result = await self.call_function(fn_index, inputs, iterator)
  File "/home/lasal/Development/test/test/lib/python3.10/site-packages/gradio/blocks.py", line 697, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/lasal/Development/test/test/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/lasal/Development/test/test/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/lasal/Development/test/test/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    re

In [79]:
!pip install gradio jinja2

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.3/5.3 MB 7.0 MB/s eta 0:00:00m eta 0:00:010:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.4/55.4 kB 1.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 3.8 MB/s eta 0:00:00m eta 0:00:010:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 682.2/682.2 kB 5.0 MB/s eta 0:00:00m eta 0:00:010:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 138.8/138.8 kB 2.1 MB/s eta 0:00:00 MB/s eta 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.8/84.8 kB 2.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.7/143.7 kB 3.4 MB/s eta 0:00:00 MB/s eta 0:00:01
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 5.7 MB/s eta 0:00:00m eta 0:00:010:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 212.9/212.9 kB 3.7 MB/s eta 0:00:009.0 MB/s eta 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.9/54.9 kB 1.1 MB/

In [89]:
import tensorflow as tf
import gradio as gr


In [90]:
interface = gr.Interface(fn=score_comment, inputs=gr.inputs.Textbox(lines=2, placeholder='Comment to score'),outputs='text')

In [91]:
interface.launch(share=True)

Running on local URL:  http://127.0.0.1:7861
Running on public URL: https://42af94f6ec7aae28.gradio.app

This share link expires in 72 hours. For free permanent hosting and GPU upgrades (NEW!), check out Spaces: https://huggingface.co/spaces


(<gradio.routes.App at 0x7fe0d9f7ca00>,
 'http://127.0.0.1:7861/',
 'https://42af94f6ec7aae28.gradio.app')

1/1 [==============================] - 0s 114ms/step
